tree_generator::SubTreeFromKF Class Reference
#include <TreeFromKF.hpp>
Public Member Functions
SubTreeFromKF ()
~SubTreeFromKF ()
bool loadLabel (std::string label)
json createSubTree (std::vector< int > &indices)
Private Member Functions
json modifyId (json node, std::vector< int > &indices)
Private Attributes
ros::NodeHandle nh_
json subtree_
std::ifstream file_
bool has_label_
std::string current_id_
Detailed Description
This class constructs one pre-defined BT subtree, given the semantic information contained in a keyframe.
The files describing the subtrees are defined in the /data/subtrees directory, and must have names matching the labels loaded in the parameter server.
Definition at line 22 of file TreeFromKF.hpp.
Constructor & Destructor Documentation
tree_generator::SubTreeFromKF::SubTreeFromKF ()
Definition at line 6 of file TreeFromKF.cpp.
References has_label_, and nh_.
tree_generator::SubTreeFromKF::~SubTreeFromKF () [inline]
Definition at line 25 of file TreeFromKF.hpp.
Member Function Documentation
json tree_generator::SubTreeFromKF::createSubTree (std::vector< int > & indices)
Definition at line 53 of file TreeFromKF.cpp.
References file_, has_label_, modifyId(), and subtree_.
Referenced by tree_generator::TreeFromKF::createTree().
bool tree_generator::SubTreeFromKF::loadLabel (std::string label)
Recovers a BT subtree with a label that matches the keyframe.
Parameters
label The KF label that identifies the subtree.
Returns
True in case the label exists and the file is recovered. False otherwise.
Definition at line 26 of file TreeFromKF.cpp.
References file_, has_label_, nh_, and tree_generator::replaceWithUnderscore().
Referenced by tree_generator::TreeFromKF::createTree().
json tree_generator::SubTreeFromKF::modifyId (json node, std::vector< int > & indices) [private]
Make sure that the created json subtree has nodes with proper indices.
Parameters
node The JSON node with the subtree description.
indices The vector of indices.
Returns
The modified json NODE.
Exceptions
logic_error
Definition at line 77 of file TreeFromKF.cpp.
References tree_generator::ACTION, tree_generator::CONDITION, tree_generator::SEL, tree_generator::SELSTAR, tree_generator::SEQ, and tree_generator::SEQSTAR.
Referenced by createSubTree().
Field Documentation
std::string tree_generator::SubTreeFromKF::current_id_ [private]
Definition at line 52 of file TreeFromKF.hpp.
std::ifstream tree_generator::SubTreeFromKF::file_ [private]
Definition at line 50 of file TreeFromKF.hpp.
Referenced by createSubTree(), and loadLabel().
bool tree_generator::SubTreeFromKF::has_label_ [private]
Definition at line 51 of file TreeFromKF.hpp.
Referenced by createSubTree(), loadLabel(), and SubTreeFromKF().
ros::NodeHandle tree_generator::SubTreeFromKF::nh_ [private]
Definition at line 48 of file TreeFromKF.hpp.
Referenced by loadLabel(), and SubTreeFromKF().
json tree_generator::SubTreeFromKF::subtree_ [private]
Definition at line 49 of file TreeFromKF.hpp.
Referenced by createSubTree().
The documentation for this class was generated from the following files:
TreeFromKF.hpp
TreeFromKF.cpp