tree_generator::TreeFromKF Class Reference
#include <TreeFromKF.hpp>
Public Member Functions
TreeFromKF ()
~TreeFromKF ()
json createTree (const std::vector< sarafun_msgs::KeyframeMsg > &keyframes_list)
Private Member Functions
void addChildren (const json &tree, std::map< std::string, json > &children_map)
Private Attributes
std::vector< int > indices_
json tree_
SubTreeFromKF subtree_parser_
Detailed Description
Creates a JSON behavior tree description from a sequence of keyframe labels. It works by aggregating different subtrees defined for each label.
Definition at line 69 of file TreeFromKF.hpp.
Constructor & Destructor Documentation
tree_generator::TreeFromKF::TreeFromKF ()
Definition at line 114 of file TreeFromKF.cpp.
References indices_.
tree_generator::TreeFromKF::~TreeFromKF () [inline]
Definition at line 73 of file TreeFromKF.hpp.
Member Function Documentation
void tree_generator::TreeFromKF::addChildren (const json & tree, std::map< std::string, json > & children_map) [private]
Definition at line 151 of file TreeFromKF.cpp.
Referenced by createTree().
json tree_generator::TreeFromKF::createTree (const std::vector< sarafun_msgs::KeyframeMsg > & keyframes_list)
Creates a JSON BT description from a sequence of keyframe labels.
Parameters
keyframes_list The list of received keyframe messages.
Returns
The JSON node representing the JSON BT description.
Definition at line 119 of file TreeFromKF.cpp.
References addChildren(), tree_generator::SubTreeFromKF::createSubTree(), indices_, tree_generator::SubTreeFromKF::loadLabel(), and subtree_parser_.
Field Documentation
std::vector<int> tree_generator::TreeFromKF::indices_ [private]
Definition at line 84 of file TreeFromKF.hpp.
Referenced by createTree(), and TreeFromKF().
SubTreeFromKF tree_generator::TreeFromKF::subtree_parser_ [private]
Definition at line 87 of file TreeFromKF.hpp.
Referenced by createTree().
json tree_generator::TreeFromKF::tree_ [private]
Definition at line 86 of file TreeFromKF.hpp.
The documentation for this class was generated from the following files:
TreeFromKF.hpp
TreeFromKF.cpp