bt_parser::Parser Class Reference
#include <parse_tree.h>
Public Member Functions
Parser (std::string filepath)
~Parser ()
BT::TreeNode * parseTree ()
Private Member Functions
BT::TreeNode * parseTree (json node)
void verifyNode (json node)
Private Attributes
std::ifstream file_
json tree_j_
std::string current_id_
Detailed Description
Implements a behavior tree parser, that reads a JSON file describing the tree and generates the executable tree structure.
Definition at line 17 of file parse_tree.h.
Constructor & Destructor Documentation
bt_parser::Parser::Parser (std::string filepath)
Parameters
filepath The directory of the JSON tree description.
Definition at line 5 of file parse_tree.cpp.
References file_.
bt_parser::Parser::~Parser ()
Definition at line 6 of file parse_tree.cpp.
References file_.
Member Function Documentation
BT::TreeNode * bt_parser::Parser::parseTree ()
Definition at line 29 of file parse_tree.cpp.
References current_id_, file_, and tree_j_.
Referenced by parseTree().
BT::TreeNode * bt_parser::Parser::parseTree (json node) [private]
Definition at line 56 of file parse_tree.cpp.
References current_id_, parseTree(), tree_j_, and verifyNode().
void bt_parser::Parser::verifyNode (json node) [private]
Verifies the sanity of the given JSON node describing a BT subtree.
Parameters
node A json node object with a BT subtree.
Exceptions
logic_error
Definition at line 8 of file parse_tree.cpp.
Referenced by parseTree().
Field Documentation
std::string bt_parser::Parser::current_id_ [private]
Definition at line 36 of file parse_tree.h.
Referenced by parseTree().
std::ifstream bt_parser::Parser::file_ [private]
Definition at line 34 of file parse_tree.h.
Referenced by Parser(), parseTree(), and ~Parser().
json bt_parser::Parser::tree_j_ [private]
Definition at line 35 of file parse_tree.h.
Referenced by parseTree().
The documentation for this class was generated from the following files:
parse_tree.h
parse_tree.cpp